### ISSUE TITLE
Update 1.5.0 Crash

### ISSUE THREAD

**Issue by TuandorGaming** [anarisis/Grindergard-Revolution#1]
Hi Dylan

I get a "Supplementaries can't load" kind of error with the new update. Is this a me problem?

Cheers
Ben [(TuandorGaming)[](url)](url)
[crash-2023-03-06_20.16.28-fml.txt](https://github.com/anarisis/Grindergard-Revolution/files/10897007/crash-2023-03-06_20.16.28-fml.txt)

**Comment by anarisis** [comment]
Thanks for the heads up! I've identified the problem and there will be a hotfix available momentarily versioned 1.5.0a.
