### ISSUE TITLE
Error loading 1.6.0

### ISSUE THREAD

**Issue by TuandorGaming** [anarisis/Grindergard-Revolution#2]
Hi Dylan

Sorry to do this again, but I'm receiving an error with the 1.6.0 update:

"Failure message: JourneyMap Integration (jmi) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: Cannot read field "version" because "this.existVersion" is null"

The exact message was the same on both my laptop and desktop installs.

I meant to report this a few days ago, sorry.

Cheers
Ben
(TuandorGaming)

**Comment by anarisis** [comment]
This is an issue with the first boot and should be fixed in the next update. For now, simply closing the game and reopening it after that first launch *should* do the trick.

**Comment by TuandorGaming** [comment]
I guess I'm worthy of the "should" modifier! I had tried several times on both computers before and tried again a couple of times just now...no dice.

All good. I've continued playing the previous version so can wait until you get the chance to update again.

**Comment by anarisis** [comment]
As a stopgap, if you know how to get into your Minecraft folder, you can copy defaultconfig.json from the JourneyMap folder in an earlier version, then paste it back into the JourneyMap folder after updating.
